1 PRINT "RAMSEY NASSER"
2 GET J$
3 PRINT "@RA"
4 GET J$
5 PRINT "HTTP://NAS.SR/"
6 GET J$
21 PRINT "TYPICAL HACKER STORY"
22 GET J$
30 PRINT "ASKED MY FATHER HOW VIDEO GAMES ARE MADE"
40 GET J$
50 PRINT "HE GAVE ME A 'BASIC' BOOK"
60 GET J$
70 PRINT "STARTED COPYING CODE EXAMPLES"
80 GET J$
81 PRINT "NO IDEA WHAT I WAS DOING"
82 GET J$
83 PRINT "TRIAL AND ERROR"
84 GET J$
90 PRINT "HAVING THE TIME OF MY LIFE"
100 GET J$
110 PRINT "WANT TO LEARN EVERYTHING ABOUT THESE MACHINES"
120 GET J$
